/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../sanity.schema.json
export type FaqBlock = {
  _type: 'faqBlock'
  items: Array<
    {
      _key: string
    } & FaqItem
  >
}

export type MediaCarousel = {
  _type: 'mediaCarousel'
  title?: string
  slides: Array<
    {
      _key: string
    } & CarouselSlide
  >
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type Media = {
  _type: 'media'
  mediaType: MediaType
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  video?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  caption?: string
}

export type Stats = {
  _type: 'stats'
  items: Array<
    {
      _key: string
    } & StatsItem
  >
}

export type PullQuote = {
  _type: 'pullQuote'
  quoteText: string
  authorName?: string
  authorTitle?: string
  authorImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type CalloutInline = {
  _type: 'calloutInline'
  theme?: BlogTheme
  showLogo?: boolean
  showCta?: boolean
  title: string
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ctaText?: string
  ctaLink?: CtaLink
}

export type CtaSmallBlock = {
  _type: 'ctaSmallBlock'
  theme?: BlogTheme
  title: string
  description?: string
  ctaText?: string
  link?: CtaLink
}

export type CtaDownloadBlock = {
  _type: 'ctaDownloadBlock'
  title: string
  previewImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  ctaText?: string
  downloadAsset: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
}

export type CtaCustomBlock = {
  _type: 'ctaCustomBlock'
  title: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  ctaText?: string
  link?: CtaLink
}

export type CtaFullWidthBlock = {
  _type: 'ctaFullWidthBlock'
  title: string
  backgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  primaryButton?: CtaLink
  secondaryButton?: CtaLink
}

export type CtaEvergreenBlock = {
  _type: 'ctaEvergreenBlock'
  theme?: BlogTheme
  title: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  primaryButton?: CtaLink
  secondaryButton?: CtaLink
}

export type HubspotFormModal = {
  _type: 'hubspotFormModal'
  ctaText: string
  modalHeading: string
  modalText?: string
  hubspotFormId: string
  hubspotCustomFields?: string
  successCopy: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type Embed = {
  _type: 'embed'
  provider: 'twitter' | 'linkedin' | 'slideshare'
  embedCode: string
}

export type BlockquoteStandalone = {
  _type: 'blockquoteStandalone'
  quote: string
  authorName?: string
  authorTitle?: string
}

export type QuoteReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'quote'
}

export type BlockquoteLinked = {
  _type: 'blockquoteLinked'
  quote: QuoteReference
}

export type ResourceDownload = {
  _type: 'resourceDownload'
  title: string
}

export type Cta = {
  _type: 'cta'
  primary: CtaLink
  secondary?: CtaLink
  primaryCtaType: 'button' | 'text'
  horizontalAlignment?: HorizontalAlignment
}

export type YoutubeVideo = {
  _type: 'youtubeVideo'
  url: string
  label: string
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type VideoAsset = {
  _type: 'videoAsset'
  video: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  label: string
  autoplay?: boolean
  roundedCorners?: boolean
}

export type BlogPortableTextImage = {
  _type: 'blogPortableTextImage'
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  caption?: string
  roundedCorners?: boolean
  horizontalAlignment?: HorizontalAlignment
}

export type CarouselSlide = {
  _type: 'carouselSlide'
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  caption?: string
}

export type FaqItem = {
  _type: 'faqItem'
  question: string
  answer: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type StatsItem = {
  _type: 'statsItem'
  label: string
  value: string
  description?: string
}

export type MediaType = 'image' | 'video'

export type BlogArticleReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'blogArticle'
}

export type CtaLink = {
  _type: 'ctaLink'
  label?: string
  href?: string
  internalRef?: BlogArticleReference
  openInNewTab?: boolean
}

export type BlogTheme = 'default' | 'light' | 'dark' | 'brand' | 'accent'

export type HorizontalAlignment = 'left' | 'center' | 'right'

export type Icon = {
  _type: 'icon'
  name?:
    | 'add-column-left'
    | 'add-column-right'
    | 'add-link'
    | 'add-reaction'
    | 'add-row-above'
    | 'add-row-below'
    | 'adjust-tone'
    | 'ai'
    | 'ai-agent'
    | 'ai-compose'
    | 'alarm-clock'
    | 'alert-circle'
    | 'alert-hexagon'
    | 'alert-square'
    | 'alert-triangle'
    | 'align-left'
    | 'align-vertical-center'
    | 'archive'
    | 'archive-off'
    | 'arrow-block-left'
    | 'arrow-block-right'
    | 'arrow-circle-broken-right'
    | 'arrow-narrow-down'
    | 'arrow-narrow-down-right'
    | 'arrow-narrow-left'
    | 'arrow-narrow-right'
    | 'arrow-narrow-up'
    | 'arrow-narrow-up-right'
    | 'at-sign'
    | 'audit-log'
    | 'autopilot'
    | 'badge-counter'
    | 'bar-chart-01'
    | 'bar-chart-10'
    | 'bell-01'
    | 'bell-off-01'
    | 'block-corner-up-left'
    | 'block-corner-up-right'
    | 'bold-01'
    | 'book-closed'
    | 'book-open-01'
    | 'bookmark'
    | 'brackets-ellipses'
    | 'brain'
    | 'branching-rule'
    | 'briefcase-01'
    | 'briefcase-01-plus'
    | 'briefcase-02'
    | 'building-05'
    | 'business-hours'
    | 'calendar'
    | 'calendar-check-02'
    | 'calendar-date'
    | 'calendar-plus-02'
    | 'caret-collapse'
    | 'caret-expand'
    | 'caret-up-down'
    | 'chat'
    | 'chat-deflected'
    | 'check'
    | 'check-circle'
    | 'check-square'
    | 'check-verified-02'
    | 'chevron-down'
    | 'chevron-left'
    | 'chevron-right'
    | 'chevron-up'
    | 'circle'
    | 'clock'
    | 'clock-check'
    | 'clock-recently-viewed'
    | 'clock-rewind'
    | 'clock-snooze'
    | 'cloud-off'
    | 'code-01'
    | 'columns-03'
    | 'compass'
    | 'connectors'
    | 'contact-auto'
    | 'contrast-02'
    | 'conversation'
    | 'conversation-search'
    | 'copilot'
    | 'copy-01'
    | 'copy-06'
    | 'copy-file'
    | 'corner-down-right'
    | 'corner-up-left'
    | 'corner-up-left-double'
    | 'corner-up-right'
    | 'cpu-chip-01'
    | 'credit-card-02'
    | 'crown'
    | 'cube-01'
    | 'cube-01-off'
    | 'cube-outline'
    | 'currency-dollar'
    | 'cursor-click'
    | 'customer-portal'
    | 'dataflow-02'
    | 'delete'
    | 'deliverability'
    | 'diamond-01'
    | 'discussions'
    | 'discussions-depreciated'
    | 'distribute-spacing-vertical'
    | 'divider'
    | 'donut-chart'
    | 'door-open'
    | 'dot'
    | 'dotpoints-01'
    | 'dots-grid'
    | 'dots-horizontal'
    | 'dots-vertical'
    | 'download-02'
    | 'edit-01'
    | 'edit-05'
    | 'emoji'
    | 'emoji-activity'
    | 'emoji-food'
    | 'emoji-nature'
    | 'emoji-symbols'
    | 'expand-01'
    | 'export'
    | 'eye'
    | 'eye-off'
    | 'face-happy'
    | 'face-smile'
    | 'feather'
    | 'field-custom'
    | 'file-02'
    | 'file-05'
    | 'file-check-01'
    | 'file-check-02'
    | 'file-download-02'
    | 'file-download-03'
    | 'file-search-01'
    | 'filter-lines'
    | 'first-page'
    | 'fix-grammar'
    | 'flag-01'
    | 'flip-backward'
    | 'flip-forward-plus'
    | 'focus'
    | 'folder'
    | 'formatting'
    | 'formatting-list'
    | 'formatting-quote'
    | 'forward-10s'
    | 'front-logo'
    | 'geometry'
    | 'gif'
    | 'gift-01'
    | 'git-branch-01'
    | 'git-pull-request'
    | 'globe-01'
    | 'globe-04'
    | 'go-to-conversation'
    | 'grab-handle'
    | 'graduation-hat-01'
    | 'grid-01'
    | 'hash-02'
    | 'heart'
    | 'help-center'
    | 'help-circle'
    | 'home-05'
    | 'hourglass-02'
    | 'hourglass-check'
    | 'image-03'
    | 'inbox-01'
    | 'inbox-list'
    | 'info-circle'
    | 'info-history'
    | 'italic-01'
    | 'keyboard-02'
    | 'laptop'
    | 'last-page'
    | 'layers-three-01'
    | 'layout-alt-01'
    | 'layout-alt-02'
    | 'layout-grid-02'
    | 'layout-left'
    | 'layout-right'
    | 'lightbulb-04'
    | 'lightning-01'
    | 'line-chart-up-01'
    | 'linear-rule'
    | 'link-03'
    | 'link-broken-03'
    | 'link-external-02'
    | 'link-to'
    | 'lock-01'
    | 'log-in-02'
    | 'log-out-02'
    | 'log-out-04'
    | 'longer'
    | 'mail-01'
    | 'mail-04'
    | 'mail-notification'
    | 'marker-pin-01'
    | 'menu-01'
    | 'menu-04'
    | 'merge'
    | 'message-plus-circle'
    | 'message-square-01'
    | 'message-template'
    | 'message-text-circle-02'
    | 'microphone-01'
    | 'minimize-01'
    | 'minus'
    | 'minus-circle'
    | 'moon-02'
    | 'numbers'
    | 'open'
    | 'outbox'
    | 'package'
    | 'paperclip'
    | 'paragraph-spacing'
    | 'pause'
    | 'pause-circle'
    | 'pencil-01'
    | 'phone'
    | 'phone-call-01'
    | 'phone-call-03'
    | 'phone-call-answered'
    | 'phone-call-ended'
    | 'phone-hang-up'
    | 'phone-incoming-01'
    | 'phone-outgoing-01'
    | 'phone-outgoing-02'
    | 'phone-pause'
    | 'phone-x'
    | 'pie-chart-01'
    | 'pin-02'
    | 'plane'
    | 'play'
    | 'play-circle'
    | 'playbook-temporary'
    | 'plus'
    | 'plus-circle'
    | 'printer'
    | 'puzzle-piece'
    | 'q-a-smart'
    | 'refresh-cw-01'
    | 'refresh-cw-02'
    | 'reopen'
    | 'repeat-01'
    | 'repeat-02'
    | 'replace-all'
    | 'rewind-10s'
    | 'rocket-02'
    | 'rule-tester'
    | 'save'
    | 'schedule'
    | 'search-sm'
    | 'send'
    | 'send-04'
    | 'send-options'
    | 'settings-02'
    | 'settings-03'
    | 'shift'
    | 'shorter'
    | 'shuffle'
    | 'sidebar'
    | 'slash-circle-01'
    | 'sliders-04'
    | 'sms'
    | 'split'
    | 'square'
    | 'star-04'
    | 'stars-01'
    | 'status-change'
    | 'sticker-square'
    | 'strikethrough-01'
    | 'sun'
    | 'switch-horizontal-01'
    | 'switch-vertical-01'
    | 'table'
    | 'tag-03'
    | 'tag-04'
    | 'target-03'
    | 'target-off'
    | 'task'
    | 'task-template'
    | 'template'
    | 'thumbs-down'
    | 'thumbs-up'
    | 'ticket-01'
    | 'tool'
    | 'translate-01'
    | 'trash-03'
    | 'truck-01'
    | 'twitter-x'
    | 'type-strikethrough-01'
    | 'umbrella-03'
    | 'unassigned'
    | 'underline-01'
    | 'unpin'
    | 'user-01'
    | 'user-check-01'
    | 'user-circle'
    | 'user-edit'
    | 'user-left-01'
    | 'user-plus-01'
    | 'user-right-01'
    | 'user-right-off'
    | 'user-x-01'
    | 'users'
    | 'users-01'
    | 'users-left'
    | 'users-plus'
    | 'variable'
    | 'video-recorder'
    | 'views'
    | 'visitor-source'
    | 'voicemail'
    | 'volume-max'
    | 'whatsapp'
    | 'workspace'
    | 'workspace-stroke'
    | 'x-circle'
    | 'x-close'
}

export type Exploration = {
  _type: 'exploration'
  theme?: Theme
  title?: string
  items?: Array<
    {
      _key: string
    } & FeatureItem
  >
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type FeatureItem = {
  _type: 'featureItem'
  icon?: Icon
  title?: string
  link?: Link
}

export type ButtonPair = {
  _type: 'buttonPair'
  variant?: 'filledOutline' | 'filledTertiary'
  firstButton?: Button
  hasSecondButton?: boolean
  secondButton?: Button
}

export type ZigZagItem = {
  _type: 'zigZagItem'
  textCombination?: TextCombination
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  hasButtonPair?: boolean
  buttonPair?: ButtonPair
  checkListItems?: Array<string>
}

export type ZigZag = {
  _type: 'zigZag'
  theme?: Theme
  textCombination?: TextCombination
  zigZagItems?: Array<
    {
      _key: string
    } & ZigZagItem
  >
}

export type TextCombination = {
  _type: 'textCombination'
  eyebrow?: string
  title: string
  description?: BlockContentTextOnly
}

export type Theme = {
  _type: 'theme'
  name?: 'theme-white' | 'theme-gray' | 'theme-dark-violet'
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: PageReference
  post?: PostReference
  openInNewTab?: boolean
}

export type CallToAction = {
  _type: 'callToAction'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  button?: Button
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  theme?: 'light' | 'dark'
  contentAlignment?: 'textFirst' | 'imageFirst'
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: PageReference
        post?: PostReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | ({
      _key: string
    } & BlogPortableTextImage)
>

export type Button = {
  _type: 'button'
  buttonText?: string
  action?: 'demo' | 'trial' | 'url'
  link?: Link
}

export type Quote = {
  _id: string
  _type: 'quote'
  _createdAt: string
  _updatedAt: string
  _rev: string
  quote: string
  authorName?: string
  authorTitle?: string
}

export type BlogArticle = {
  _id: string
  _type: 'blogArticle'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  blogArticleContent?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href: string
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & BlogPortableTextImage)
    | ({
        _key: string
      } & VideoAsset)
    | ({
        _key: string
      } & YoutubeVideo)
    | ({
        _key: string
      } & Cta)
    | ({
        _key: string
      } & ResourceDownload)
    | ({
        _key: string
      } & BlockquoteLinked)
    | ({
        _key: string
      } & BlockquoteStandalone)
    | ({
        _key: string
      } & Embed)
    | ({
        _key: string
      } & HubspotFormModal)
    | ({
        _key: string
      } & CtaEvergreenBlock)
    | ({
        _key: string
      } & CtaFullWidthBlock)
    | ({
        _key: string
      } & CtaCustomBlock)
    | ({
        _key: string
      } & CtaDownloadBlock)
    | ({
        _key: string
      } & CtaSmallBlock)
    | ({
        _key: string
      } & CalloutInline)
    | ({
        _key: string
      } & PullQuote)
    | ({
        _key: string
      } & Stats)
    | ({
        _key: string
      } & Media)
    | ({
        _key: string
      } & MediaCarousel)
    | ({
        _key: string
      } & FaqBlock)
  >
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: PageReference
      post?: PostReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  heading: string
  subheading?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
    | ({
        _key: string
      } & ZigZag)
    | ({
        _key: string
      } & Exploration)
  >
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: BlockContent
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: PersonReference
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | FaqBlock
  | MediaCarousel
  | SanityImageAssetReference
  | SanityFileAssetReference
  | Media
  | Stats
  | PullQuote
  | CalloutInline
  | CtaSmallBlock
  | CtaDownloadBlock
  | CtaCustomBlock
  | CtaFullWidthBlock
  | CtaEvergreenBlock
  | HubspotFormModal
  | Embed
  | BlockquoteStandalone
  | QuoteReference
  | BlockquoteLinked
  | ResourceDownload
  | Cta
  | YoutubeVideo
  | VideoAsset
  | BlogPortableTextImage
  | CarouselSlide
  | FaqItem
  | StatsItem
  | MediaType
  | BlogArticleReference
  | CtaLink
  | BlogTheme
  | HorizontalAlignment
  | Icon
  | Exploration
  | FeatureItem
  | ButtonPair
  | ZigZagItem
  | ZigZag
  | TextCombination
  | Theme
  | PageReference
  | PostReference
  | Link
  | CallToAction
  | InfoSection
  | BlockContentTextOnly
  | BlockContent
  | Button
  | Quote
  | BlogArticle
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Settings
  | Page
  | PersonReference
  | Post
  | Person
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol
